version: '3.8'
services:
  redis:
    image: redis:7

  web:
    build: .
    command: gunicorn synapse_project.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile -
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./test_reports:/test_reports

  worker:
    build: .
    command: celery -A synapse_project worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
