# Generated by Django 4.2.27 on 2026-01-13 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
