# Generated by Django 4.2.27 on 2026-01-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_cohort_alter_enrollment_course'),
        ('submissions', '0003_problem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='courses.course'),
        ),
    ]
