# Generated by Django 4.2.27 on 2026-01-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_cohort_alter_enrollment_course'),
        ('submissions', '0004_problem_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem', to='courses.lesson'),
        ),
    ]
