# Generated by Django 4.2.27 on 2026-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_problem_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='initial_code',
            field=models.TextField(blank=True, help_text='Initial code shown to the student'),
        ),
        migrations.AddField(
            model_name='problem',
            name='public_tests',
            field=models.TextField(blank=True, help_text='Units tests visible to the student (JSON or text).'),
        ),
    ]
