from rest_framework import viewsets, status, permissions
from rest_framework.decorators import action
from rest_framework.response import Response
from django.db.models import Count, Q
from .models import Course, Cohort, Module, Lesson, Enrollment, Progress
from submissions.models import Submission
from .serializers import (
    CourseSerializer, CohortSerializer, ModuleSerializer,
    LessonSerializer, EnrollmentSerializer
)
from .permissions import IsStaffOrReadOnly, IsInstructorOrStaff
from drf_spectacular.utils import extend_schema_view, extend_schema, OpenApiExample
import logging

from dimensional.filament import (
    EventDimensions,
    EventVector,
    EventState,
    FilamentDecision,
    FilamentDecisionService,
    default_filament_hooks,
)

logger = logging.getLogger(__name__)

# telemetry SDK (resilient)
from telemetry import sdk as telemetry

enrollment_filament_service = FilamentDecisionService(
    hooks=default_filament_hooks(),
    risk_threshold=0.85,
)


@extend_schema_view(
    create=extend_schema(
        request=CourseSerializer,
        examples=[
            OpenApiExample(
                'Create Course Example',
                value={
                    'title': 'Introdução à IA',
                    'description': 'Curso prático de introdução à inteligência artificial',
                    'level': 'beginner',
                    'price': '0.00'
                },
            ),
        ],
    ),
    enroll=extend_schema(
        request=EnrollmentSerializer,
        responses={201: EnrollmentSerializer},
        description="Enroll the current user in a course and optionally a cohort."
    )
)
class CourseViewSet(viewsets.ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    permission_classes = [IsStaffOrReadOnly, IsInstructorOrStaff]

    def get_queryset(self):
        queryset = super().get_queryset()
        level = self.request.query_params.get('level')
        search = self.request.query_params.get('search')
        min_price = self.request.query_params.get('min_price')
        max_price = self.request.query_params.get('max_price')
        is_published = self.request.query_params.get('is_published')
        
        if level:
            queryset = queryset.filter(level=level)
        if search:
            queryset = queryset.filter(Q(title__icontains=search) | Q(description__icontains=search))
        if min_price:
            queryset = queryset.filter(price__gte=min_price)
        if max_price:
            queryset = queryset.filter(price__lte=max_price)
        if is_published is not None:
            queryset = queryset.filter(is_published=is_published.lower() == 'true')
            
        return queryset

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

    @action(detail=False, methods=['get'], permission_classes=[permissions.IsAuthenticated])
    def my_courses(self, request):
        """Returns courses the current user is enrolled in."""
        enrollments = Enrollment.objects.filter(user=request.user, is_active=True).select_related('course')
        courses = [e.course for e in enrollments]
        page = self.paginate_queryset(courses)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)
            
        serializer = self.get_serializer(courses, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['post'], permission_classes=[permissions.IsAuthenticated])
    def enroll(self, request, pk=None):
        course = self.get_object()
        # correlation id propagation: prefer incoming header, else will be generated by telemetry.emit
        correlation_id = request.headers.get('X-Correlation-ID') or request.META.get('HTTP_X_CORRELATION_ID')
        cohort_id = request.data.get('cohort')
        cohort = None
        
        if cohort_id:
            try:
                cohort = Cohort.objects.get(id=cohort_id, course=course)
            except Cohort.DoesNotExist:
                return Response({"error": "Cohort not found for this course"}, status=status.HTTP_400_BAD_REQUEST)
            
            if not cohort.enrollment_open:
                return Response({"error": "Enrollment for this cohort is closed"}, status=status.HTTP_400_BAD_REQUEST)
            
            if cohort.enrollments.count() >= cohort.capacity:
                return Response({"error": "Cohort is at full capacity"}, status=status.HTTP_400_BAD_REQUEST)

        existing_enrollment = Enrollment.objects.filter(user=request.user, course=course, is_active=True)
        duplicate_enrollment = existing_enrollment.exists()
        cohort_open = bool(cohort and cohort.enrollment_open)
        cohort_capacity = getattr(cohort, 'capacity', None)
        cohort_populated = cohort.enrollments.count() if cohort else 0
        risk_score = ((cohort_populated + 1) / max(cohort_capacity, 1)) if cohort_capacity else 0.0

        event_dimensions = EventDimensions(
            identidade={
                'user_id': request.user.id,
                'role': getattr(request.user, 'role', 'student'),
                'user_active': request.user.is_active,
                'is_verified': bool(getattr(request.user, 'email', None)),
            },
            contexto={
                'course_id': course.id,
                'course_active': getattr(course, 'is_published', True),
                'cohort_id': cohort.id if cohort else None,
                'cohort_open': cohort_open or cohort is None,
            },
            dependencia={
                'duplicate': duplicate_enrollment,
                'cohort_locked': not cohort_open,
            },
            risco={
                'capacity': cohort_capacity,
                'current': cohort_populated,
                'score': risk_score,
            },
        )

        enrollment_vector = EventVector(
            name='CourseEnrollment',
            module='courses.CourseViewSet.enroll',
            story_id='BACKLOG-1234',
            dimensions=event_dimensions,
            payload={
                'course_id': course.id,
                'requested_cohort': cohort_id,
                'caller': request.user.username,
                'correlation_id': correlation_id,
            },
        )
        enrollment_vector.advance_state(EventState.S1A)
        # Emit S1a telemetry (submission click / intent)
        telemetry.emit('CourseEnrollment.S1a', {
            'correlation_id': correlation_id,
            'story_id': enrollment_vector.story_id,
            'user_id': request.user.id,
            'course_id': course.id,
        })

        enrollment_vector.advance_state(EventState.S1B)
        telemetry.emit('CourseEnrollment.S1b', {
            'correlation_id': correlation_id,
            'story_id': enrollment_vector.story_id,
            'user_id': request.user.id,
            'course_id': course.id,
        })

        decision_summary = enrollment_filament_service.process(enrollment_vector, EventState.S2)
        # Emit S2 telemetry with filamento decision
        telemetry.emit('CourseEnrollment.S2', {
            'correlation_id': correlation_id,
            'story_id': enrollment_vector.story_id,
            'user_id': request.user.id,
            'course_id': course.id,
            'decision': decision_summary.decision.value,
            'reason': decision_summary.message,
        })
        if decision_summary.decision == FilamentDecision.BLOQUEAR:
            enrollment_filament_service.record_learning(enrollment_vector, decision_summary.message)
            telemetry.emit('CourseEnrollment.S4', {
                'correlation_id': correlation_id,
                'story_id': enrollment_vector.story_id,
                'user_id': request.user.id,
                'course_id': course.id,
                'decision': decision_summary.decision.value,
                'reason': decision_summary.message,
            })
            return Response(
                {
                    'error': 'Filamento bloqueou o enrolamento',
                    'reason': decision_summary.message,
                },
                status=status.HTTP_400_BAD_REQUEST,
            )
        if decision_summary.decision == FilamentDecision.AJUSTAR:
            logger.info(
                'Ajuste sugerido pelo filamento para enrolamento',
                extra={
                    'story_id': enrollment_vector.story_id,
                    'reason': decision_summary.message,
                },
            )

        enrollment, created = Enrollment.objects.get_or_create(
            user=request.user,
            course=course,
            defaults={'cohort': cohort}
        )

        enrollment_filament_service.log_state(
            enrollment_vector,
            EventState.S3,
            FilamentDecision.ACEITAR,
            f'Matrícula persistida (created={created})',
        )
        # Emit S3 telemetry after persistence
        telemetry.emit('CourseEnrollment.S3', {
            'correlation_id': correlation_id,
            'story_id': enrollment_vector.story_id,
            'user_id': request.user.id,
            'course_id': course.id,
            'created': bool(created),
        })

        enrollment_filament_service.record_learning(
            enrollment_vector,
            "Aprendizado registrado após persistência",
            FilamentDecision.ACEITAR,
            state=EventState.S4,
        )
        telemetry.emit('CourseEnrollment.S4', {
            'correlation_id': correlation_id,
            'story_id': enrollment_vector.story_id,
            'user_id': request.user.id,
            'course_id': course.id,
            'decision': FilamentDecision.ACEITAR.value,
        })
        
        if not created:
            if cohort and enrollment.cohort != cohort:
                enrollment.cohort = cohort
                enrollment.save()
            return Response({"message": "User already enrolled"}, status=status.HTTP_200_OK)

        serializer = EnrollmentSerializer(enrollment)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class ModuleViewSet(viewsets.ModelViewSet):
    queryset = Module.objects.all()
    serializer_class = ModuleSerializer
    permission_classes = [IsInstructorOrStaff]


class LessonViewSet(viewsets.ModelViewSet):
    queryset = Lesson.objects.all()
    serializer_class = LessonSerializer
    permission_classes = [IsInstructorOrStaff]


@extend_schema_view(
    create=extend_schema(
        request=CohortSerializer,
        examples=[
            OpenApiExample(
                'Create Cohort Example',
                value={
                    'course': 1,
                    'title': 'Turma 01',
                    'start_date': '2026-01-05',
                    'end_date': '2026-03-05',
                    'capacity': 30,
                    'timezone': 'UTC'
                },
            ),
        ],
    )
)
class CohortViewSet(viewsets.ModelViewSet):
    queryset = Cohort.objects.select_related('course').all()
    serializer_class = CohortSerializer
    permission_classes = [IsStaffOrReadOnly]

    @action(detail=True, methods=['get'], permission_classes=[IsInstructorOrStaff])
    def members(self, request, pk=None):
        cohort = self.get_object()
        enrollments = cohort.enrollments.all()
        serializer = EnrollmentSerializer(enrollments, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['post'], permission_classes=[IsInstructorOrStaff])
    def bulk_enroll(self, request, pk=None):
        """Bulk enroll users by email list."""
        cohort = self.get_object()
        emails = request.data.get('emails', [])
        if not isinstance(emails, list):
            return Response({"error": "Emails field must be a list"}, status=status.HTTP_400_BAD_REQUEST)

        from users.models import User
        results = {"enrolled": [], "not_found": [], "already_enrolled": []}

        for email in emails:
            try:
                user = User.objects.get(email=email)
                enrollment, created = Enrollment.objects.get_or_create(
                    user=user, 
                    course=cohort.course,
                    defaults={'cohort': cohort}
                )
                if created:
                    results["enrolled"].append(email)
                else:
                    if enrollment.cohort != cohort:
                        enrollment.cohort = cohort
                        enrollment.save()
                        results["enrolled"].append(email)
                    else:
                        results["already_enrolled"].append(email)
            except User.DoesNotExist:
                results["not_found"].append(email)

        return Response(results)

    @action(detail=True, methods=['get'], permission_classes=[permissions.IsAuthenticated])
    def leaderboard(self, request, pk=None):
        cohort = self.get_object()
        # Check if user is enrolled in this cohort or is staff
        if not request.user.is_staff and not cohort.enrollments.filter(user=request.user).exists():
            return Response({"error": "You must be enrolled in this cohort to see the leaderboard."}, status=status.HTTP_403_FORBIDDEN)

        # Aggregate points: 10 points per completed lesson, 50 points per successful submission
        # This is a simplified gamification logic
        members = cohort.enrollments.select_related('user').all()
        leaderboard_data = []

        for enrollment in members:
            user = enrollment.user
            completed_lessons = Progress.objects.filter(user=user, lesson__module__course=cohort.course, is_completed=True).count()
            successful_submissions = Submission.objects.filter(user=user, problem__course=cohort.course, status='success').count()
            
            total_points = (completed_lessons * 10) + (successful_submissions * 50)
            
            leaderboard_data.append({
                "username": user.username,
                "completed_lessons": completed_lessons,
                "successful_submissions": successful_submissions,
                "total_points": total_points,
                "role": getattr(user, 'role', 'student')
            })

        # Sort by points descending
        leaderboard_data.sort(key=lambda x: x['total_points'], reverse=True)
        return Response(leaderboard_data)
